title: "Cadena de Frío"
description: "Monitoreo embebido y trazabilidad con IoT"
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "air"
markdown: kramdown
permalink: /:title/
paginate: 5
paginate_path: /page:num/
